#include <stdint.h>

#include "cchrtr.h"

CCHRTR_TYPES_BEGIN
  CCHRTR_TYPE(gcd_1)
CCHRTR_TYPES_END

#define ARGTYPES_gcd_1(DEF,SEP) DEF(arg1,uint64_t)

CCHRTR_DEF(gcd_1)

CCHRTR_DEF_DATASTRUCT

CCHRTR_CONS_BEGIN(gcd_1)
  CCHRTR_RULE_BEGIN(I)
    CCHRTR_ENSURE(I_arg1==0)
    CCHRTR_KILL_SELF
    CCHRTR_STOP
  CCHRTR_RULE_END(I)
  CCHRTR_RULE_BEGIN(J)
    CCHRTR_LOOP_BEGIN(gcd_1,I)
      CCHRTR_ENSURE_DIFF(I,J)
      CCHRTR_ENSURE(J_arg1>=I_arg1)
      CCHRTR_KILL_SELF
      CCHRTR_ADD(gcd_1,J_arg1-I_arg1)
      CCHRTR_STOP
    CCHRTR_LOOP_END(gcd_1,J)
  CCHRTR_RULE_END(I)
  CCHRTR_MAKE
  CCHRTR_RULE_BEGIN(J)
    CCHRTR_LOOP_BEGIN(gcd_1,I)
      CCHRTR_ENSURE_DIFF(I,J)
      CCHRTR_ENSURE(J_arg1 >= I_arg1)
      CCHRTR_KILL(J)
      CCHRTR_ADD(gcd_1,J_arg1-I_arg1)
    CCHRTR_LOOP_END(gcd_1,J)
  CCHRTR_RULE_END(J)
CCHRTR_CONS_END(gcd_1)

