maart.pdf: maart.dvi
	dvipdf maart.dvi

maart.dvi: maart.tex
	latex maart.tex && latex maart.tex

december.pdf: december.dvi
	dvipdf december.dvi

december.dvi: december.tex
	latex december.tex && latex december.tex

